/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[76] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "aa0",
    "aw1",
    "ah0",
    "ao1",
    "ey1",
    "ey0",
    "ih1",
    "ao0",
    "ae1",
    "ay0",
    "aw0",
    "ow0",
    "ow1",
    "ae0",
    "eh0",
    "ih0",
    "w-ey1",
    "ax0",
    "ay1",
    "ah1",
    "b",
    "ch",
    "s",
    "t-s",
    "k",
    "sh",
    "d",
    "t",
    "jh",
    "iy1",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "y-uw0",
    "uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax0-l",
    "m",
    "m-ae1",
    "ax0-m",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "r",
    "er0",
    "z",
    "th",
    "dh",
    "y-er0",
    "y-uh1",
    "y-er1",
    "y-ah0",
    "y-uh0",
    "ah0-w",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    5959, /* b */
    6011, /* c */
    6684, /* d */
    6790, /* e */
    11637, /* f */
    11640, /* g */
    12164, /* h */
    12435, /* i */
    16593, /* j */
    16730, /* k */
    16741, /* l */
    16968, /* m */
    16987, /* n */
    17559, /* o */
    21542, /* p */
    21760, /* q */
    21761, /* r */
    23711, /* s */
    24782, /* t */
    25107, /* u */
    27033, /* v */
    27040, /* w */
    27213, /* x */
    27265, /* y */
    27787, /* z */
    0
};

