/*******************************************************/
/**  Autogenerated lts rules (regex) for cmu     */
/**  from wfst/    */
/*******************************************************/

#include "cst_string.h"
#include "cst_lts.h"
#include "cst_lexicon.h"

const char * const cmu_lts_phone_table[75] = 
{
    "epsilon",
    "eh1",
    "aa1",
    "aa0",
    "aw1",
    "ax0",
    "ao1",
    "ey1",
    "ey0",
    "ao0",
    "ih1",
    "ay0",
    "ae1",
    "aw0",
    "ow0",
    "ow1",
    "ae0",
    "ih0",
    "ah1",
    "eh0",
    "w-ey1",
    "y-ax0",
    "ay1",
    "ah0",
    "b",
    "ch",
    "k",
    "s",
    "t-s",
    "sh",
    "d",
    "t",
    "jh",
    "iy1",
    "iy0",
    "uw1",
    "y-uw1",
    "oy1",
    "uw0",
    "y-uw0",
    "oy0",
    "f",
    "g",
    "zh",
    "hh",
    "y",
    "l",
    "ax0-l",
    "m",
    "ax0-m",
    "m-ae1",
    "m-ax0",
    "ng",
    "n",
    "n-y",
    "uh1",
    "uh0",
    "w",
    "w-ah1",
    "er1",
    "p",
    "er0",
    "r",
    "z",
    "th",
    "dh",
    "y-er0",
    "y-uh1",
    "y-er1",
    "v",
    "k-s",
    "g-zh",
    "k-sh",
    "g-z",
    NULL
};

const char * const cmu_lts_letter_table[30] = 
{
    "nothing",
    "#",
    "0",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    NULL
};

const cst_lts_addr cmu_lts_letter_index[27] = 
{
    0, /* a */
    5905, /* b */
    5946, /* c */
    6619, /* d */
    6730, /* e */
    11459, /* f */
    11468, /* g */
    12144, /* h */
    12403, /* i */
    16664, /* j */
    16783, /* k */
    16807, /* l */
    17366, /* m */
    17409, /* n */
    17586, /* o */
    21594, /* p */
    21627, /* q */
    21628, /* r */
    23671, /* s */
    24955, /* t */
    25439, /* u */
    27312, /* v */
    27323, /* w */
    27500, /* x */
    27547, /* y */
    28081, /* z */
    0
};

